### PR TITLE
risinghf.md

### PR DESCRIPTION
**Pull request by williamzhang22**
risinghf helium manufacturer application

### CODE REVIEW

**Comment by ChristinaR04** [comment]
Hi @williamzhang22,  it looks like there is a conflict that needs to be resolved first. Please copy the template file rather than edit it directly. This [doc ](https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/)should help.

**Comment by williamzhang22** [comment]
Hi, Christina

I submitted again. Could you pls check it again for me ? And let me know when will it be approved ?



William Zhang
Sales Manager
RuiXingHengFang Network (Shenzhen) Co.,Ltd
﻿Add: Room 201, building 6 Software Park(Phase 1), Gaoxin Mid 3rd Road, NanShan District, Shenzhen, China 518057
Cell: +86-13260615462 || Office : 0755-86529656
Wechat/Skype: 13260615462
WhatsApp: +256 701 090257
Email:  ***@***.***
Website: www.risinghf.com
Alibaba Exhibition: risinghf2020.en.alibaba.com
 
From: ChristinaR04
Date: 2021-12-17 05:44
To: dewi-alliance/hotspot-manufacturers
CC: williamzhang22; Mention
Subject: Re: [dewi-alliance/hotspot-manufacturers] risinghf.md (PR #238)
Hi @williamzhang22, it looks like there is a conflict that needs to be resolved first. Please copy the template file rather than edit it directly. This doc should help.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by williamzhang22** [comment]
Hi, Christina

I submitted risinghf.md again. Could you pls check it again for me ? And let me know when will it be approved ?


William Zhang
Sales Manager
RuiXingHengFang Network (Shenzhen) Co.,Ltd
﻿Add: Room 201, building 6 Software Park(Phase 1), Gaoxin Mid 3rd Road, NanShan District, Shenzhen, China 518057
Cell: +86-13260615462 || Office : 0755-86529656
Wechat/Skype: 13260615462
WhatsApp: +256 701 090257
Email:  ***@***.***
Website: www.risinghf.com
Alibaba Exhibition: risinghf2020.en.alibaba.com
 
From: ChristinaR04
Date: 2021-12-17 05:44
To: dewi-alliance/hotspot-manufacturers
CC: williamzhang22; Mention
Subject: Re: [dewi-alliance/hotspot-manufacturers] risinghf.md (PR #238)
Hi @williamzhang22, it looks like there is a conflict that needs to be resolved first. Please copy the template file rather than edit it directly. This doc should help.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ChristinaR04** [comment]
@williamzhang22, there is still a conflict. The template.md file should be copied. Please see this guide for help: https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/

**Comment by ChristinaR04** [comment]
Duplicate HIP19.

**Pull request closed without merging**
