### PR TITLE
Treelink-IoT - HIP19 third-party manufacturer application

### PR DESCRIPTION
**Pull request by CamelShoko**
Treelink-IoT - HIP19 third-party manufacturer application

### CODE REVIEW

**Comment by ChristinaR04** [comment]
@CamelShoko The email address provided came back, can you please an updated email.

**Comment by CamelShoko** [comment]
> @CamelShoko The email address provided came back, can you please an updated email.

Sorry, do you mean this email, 'supprot@treelink-iot.com' ?
Can i pull another request for correct it?

**Comment by CamelShoko** [comment]
> @CamelShoko The email address provided came back, can you please an updated email.

https://github.com/dewi-alliance/hotspot-manufacturers/pull/227

**Comment by ChristinaR04** [comment]
> > @CamelShoko The email address provided came back, can you please an updated email.
> 
> Sorry, do you mean this email, '[supprot@treelink-iot.com](mailto:supprot@treelink-iot.com)' ? Can i pull another request for correct it?

The email send to that address came back as "address not found". Is it supposed to be "Support"?

**Pull request merged**
