### PR TITLE
Taiwan Shengwei Electronic Technology Co., Ltd.md

### PR DESCRIPTION
**Pull request by Eroskwokgithub**

### CODE REVIEW

**Comment by ChristinaR04** [comment]
Hi @Eroskwokgithub, it looks like there is a conflict that needs to be resolved first. Please copy the template file rather than editing it directly. This [doc ](https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/)should help.

**Comment by Eroskwokgithub** [comment]
Hi Helium,Thank you for your reply. Let's take a look at the document and
resubmit it! Thanks for your support

ChristinaR04 ***@***.***> 于2021年12月15日周三 01:08写道：

**Comment by Eroskwokgithub** [comment]
Dear Helium，We have re-studied the course and submitted the manufacturer's
application here, but it is not clear whether the application is correct.
If there is any mistake, can you tell us and guide us to operate correctly?
thank you！

Eros Kwok ***@***.***> 于2021年12月15日周三 16:35写道：

**Comment by ChristinaR04** [comment]
Hi @Eroskwokgithub, there is still a conflict. The template.md file should be copied. There's a guide here: https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/

**Comment by Eroskwokgithub** [comment]
感谢你的回复。

ChristinaR04 ***@***.***> 于2021年12月21日周二 06:42写道：

**Comment by Eroskwokgithub** [comment]
Dear Helium I'm very sorry, but I don't know if it was a mistake in our
operation. We cannot open the Template.md page in the tutorial page. We
only opened the 0000-template.md page. Then we log in to
https://github.com/helium/HIP/ to find the link address of template.md, but
unfortunately we still can't find it. Finally, we found the Template.md
file at github.com/dewi-alliance/hotspot-manufacturers, and we tried to
submit it once.
There are instructions in the tutorial to paste into GithubPR. In the
0019-third-party-manufacturers directory, we didn’t understand how to do
it. Should we paste and submit once? I apologize this time because we are
not familiar with the operation of Github. Can someone guide or help us
with the correct operation? thanks




Eros Kwok ***@***.***> 于2021年12月22日周三 01:05写道：

**Comment by ChristinaR04** [comment]
Closed, duplicate HIP19 proposal.

**Pull request closed without merging**
