### PR TITLE
Create Lanodo Hotspot.md

### PR DESCRIPTION
**Pull request by lanodo**
Lanodo!!!

### CODE REVIEW

**Comment by lanodo** [comment]
Here are our Hip
https://github.com/lanodo/hotspot-manufacturers/blob/a4655054237ea8e37dc841957f365d850a7723a8/Lanodo%20Hotspot.md

**Comment by lanodo** [comment]
Details of hardware
**Indoor Version**

| Chip                        | Specifications | Remarks |
| --------------------------- | -------------- | ------- |
| 8-channel LORA module       | SX1302         | SX1302  |
| RockChip  (ARM64)           | 4GB            |         |
| ATECC608 secret key storage |                |         |
| GPS                         |                |         |
| WIFI                        |                |         |
image

**Comment by ChristinaR04** [comment]
Hi @lanodo, thank you for Lanodo's HIP19 application. This application includes both a Full Hotspot and a Light Hotspot. Due to the timeline for Light Hotspots, we are not accepting any new applications for Full Hotspots. There are also a few questions that are missing answers. This HIP19 application will need to be updated before it can be merged.

**Comment by lanodo** [comment]
Hi , we have update out hip and make answer to those question @ChristinaR04

**Comment by ChristinaR04** [comment]
@lanodo, please review the HIP19 Application, the following questions are still missing:

- Have you shipped anything in the past?
- What types of products have you shipped?
- Which countries have you previously shipped regulatory approved products? (FCC, CE, etc.)
- How will your customers be able to contact you for support for your products?
- The entire section about Manufacturing Information is missing.
- Website info is missing.

**Comment by lanodo** [comment]
> @lanodo, please review the HIP19 Application, the following questions are still missing:
> 
> * Have you shipped anything in the past?
> * What types of products have you shipped?
> * Which countries have you previously shipped regulatory approved products? (FCC, CE, etc.)
> * How will your customers be able to contact you for support for your products?
> * The entire section about Manufacturing Information is missing.
> * Website info is missing.

Hi , we have add some information about the questiones 

- Have you shipped anything in the past?
  - We manufacture more than 10k IoT gateway products every year and ship products to Europe and North America for use in traditional agriculture, education, transportation and other industries.  
- What types of products have you shipped?
  - IoT gateway, smart watch, smart water meter, smart electricity meter 
- Which countries have you previously shipped regulatory approved products? (FCC, CE, etc.)
  - Our products have ce and fcc certification, if we pass the helium audit we will quickly pass the ce, fcc certification
- How will your customers be able to contact you for support for your products?
  - Our customers contact us by email, phone, discord. Provide 24 hours support
- The entire section about Manufacturing Information is missing.
  - Lanodo has long time provide professional ODM/OEM customized services for front-line equipment/system manufacturers to domestic and foreign, including a variety of mobile terminals, medical, power, transportation, logistics, police and other industries and ventilation mobile phone terminals, from ID design, motherboard design, structural open mold design, test verification, app design, manufacturing , quality assurance, such as one-stop design and development of production services. It can meet the various vertical industry complex application needs and has a wealth of research and development experience.
- Website info is missing.
  - Our product list:http://www.lanodo.com/enlang/application.asp

**Comment by ChristinaR04** [comment]
@lanodo, this is incorrect. Please submit a new HIP19 application and answer all questions.

**Pull request closed without merging**
