### PR TITLE
Chendu ZhiJiaXin company

### PR DESCRIPTION
**Pull request by li33114413**

### CODE REVIEW

**Comment by li33114413** [comment]
Rendered view: https://github.com/li33114413/hotspot-manufacturers/blob/main/chengdu-zhijiaxin-experimental-equipment-company.md

**Comment by ChristinaR04** [comment]
Hi @li33114413, please answer the question about, _Which security implementation (ECC608, TPM, TrustZone, other) your team plans to use_. All questions are required.

**Comment by li33114413** [comment]
Thank you for your reply. We have updated the submitted information and will use TPM chip for encryption

**Comment by li33114413** [comment]
@

> Hi @li33114413, please answer the question about, _Which security implementation (ECC608, TPM, TrustZone, other) your team plans to use_. All questions are required.

**Comment by li33114413** [comment]
> Hi @li33114413, please answer the question about, _Which security implementation (ECC608, TPM, TrustZone, other) your team plans to use_. All questions are required.

Thank you for your reply. We have updated the submitted information and will use TPM chip for encryption

**Pull request merged**
