### PR TITLE
Application from Taiwan Shengwei

### PR DESCRIPTION
**Pull request by Eroskwokgithub**

### CODE REVIEW

**Comment by ChristinaR04** [comment]
Hi @Eroskwokgithub, It looks like there is still a conflict that needs to be resolved. Please refer to the guide [here](https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/).

**Comment by Eroskwokgithub** [comment]
Hi Christina, I am so sorry to need you to get back to us again and again.
Unfortunately, we read the manual and it was still wrong. Besides GitHub,
is there any other way to apply? thanks

ChristinaR04 ***@***.***> 于2022年1月19日周三 02:31写道：

**Comment by ChristinaR04** [comment]
Hi @Eroskwokgithub, Github is the only place to submit a HIP19 proposal.

**Comment by ChristinaR04** [comment]
Closed, duplicate HIP19 proposal.

**Pull request closed without merging**
